****

**Import The Necessary Libraries**

In [1]:
import numpy as np 
import pandas as pd 
import torch
import torch.nn as nn
from torchvision import transforms, datasets, models



import matplotlib.pyplot as plt

import imageio

from tqdm import tqdm


use transforms to augment data and make it so the resnet model will be able to work with our images(thay must be of size 224)

In [2]:
train_transform = transforms.Compose([
    transforms.RandomResizedCrop(size=256, scale=(0.8, 1.0)),
#     transforms.RandomRotation(degrees=(0, 180)),
#     transforms.CenterCrop(size=224),
    transforms.RandomHorizontalFlip(0.5),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

test_transform = transforms.Compose([
    transforms.Resize(size=256),
    transforms.CenterCrop(size=224),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

train_dataset = datasets.ImageFolder('/kaggle/input/intel-image-classification/seg_train/seg_train', transform=train_transform)
test_dataset = datasets.ImageFolder('/kaggle/input/intel-image-classification/seg_test/seg_test', transform=test_transform)

load the data

In [3]:
batch_size = 32
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size)


funcion defiend fo freezing and unfreezing our pre-trained model

In [4]:
def freeze_or_un_freeze(model ,val=False):
    for param in model.parameters():
        param.requires_grad = val

In [5]:
device = torch.device('cuda:0' if torch.cuda.is_available else 'cpu')
print(device)

cuda:0


defining our training and accuracy methods

In [6]:
def accuracy(out, targets):
    _, preds = torch.max(out, dim=1)
    return torch.tensor(torch.sum(preds == targets).item() / len(preds))

def train(model, criterion, optimizer, train_loader, test_loader, epochs, unfreeze_after):
    train_losses = np.zeros(epochs)
    test_losses = np.zeros(epochs)
    train_accs = np.zeros(epochs)
    test_accs = np.zeros(epochs)
    
    for _ in tqdm(range(epochs)):
        
        if _ == unfreeze_after:
            freeze_or_un_freeze(model, True)
        
        train_loss = []
        train_acc = []
        test_acc = []
        
        model.train()
        for inputs, targets in train_loader:
            inputs, targets = inputs.to(device), targets.to(device)
            
            optimizer.zero_grad()
            
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            
            loss.backward()
            optimizer.step()
            
            train_loss.append(loss.item())
            train_acc.append(accuracy(outputs, targets))
        
        train_loss = np.mean(train_loss)
        train_acc = np.mean(train_acc)
        
        test_loss = []
        
        model.eval()
        for inputs, targets in test_loader:
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            test_acc.append(accuracy(outputs, targets))

            test_loss.append(loss.item())
        test_loss = np.mean(test_loss)
        test_acc = np.mean(test_acc)
        
        train_losses[_] = train_loss
        test_losses[_] = test_loss
        train_accs[_] = train_acc
        test_accs[_] = test_acc
        
        print(f'Epoch {_+1}, Train Loss: {train_loss:.4f}, Test Loss: {test_loss:.4f}, Train Acc: {train_acc:.4f}, Test Acc: {test_acc:.4f}')
    return train_losses, test_losses, train_accs, test_accs

In [82]:
model = models.resnet101(pretrained=True)
print(model)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [83]:
freeze_or_un_freeze(model)
n = model.fc.in_features
print(n)
model.fc = nn.Sequential(
    nn.Dropout(0.2),
    nn.Linear(n, 512), 
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(512, 6),
    nn.Softmax(),
)

2048


In [7]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.00001, betas=(0, 0.999))


NameError: name 'model' is not defined

In [85]:
print(device)
model.to(device)
train(model, criterion, optimizer, train_loader, test_loader, 30, 10)

cuda:0


  3%|▎         | 1/30 [01:56<56:14, 116.37s/it]

Epoch 1, Train Loss: 1.6172, Test Loss: 1.3802, Train Acc: 0.6177, Test Acc: 0.8702


  7%|▋         | 2/30 [03:52<54:20, 116.46s/it]

Epoch 2, Train Loss: 1.3577, Test Loss: 1.2465, Train Acc: 0.8546, Test Acc: 0.8865


 10%|█         | 3/30 [05:48<52:19, 116.28s/it]

Epoch 3, Train Loss: 1.2736, Test Loss: 1.2082, Train Acc: 0.8671, Test Acc: 0.8912


 13%|█▎        | 4/30 [07:45<50:23, 116.27s/it]

Epoch 4, Train Loss: 1.2385, Test Loss: 1.1901, Train Acc: 0.8751, Test Acc: 0.8922


 17%|█▋        | 5/30 [09:41<48:28, 116.34s/it]

Epoch 5, Train Loss: 1.2188, Test Loss: 1.1797, Train Acc: 0.8799, Test Acc: 0.8935


 20%|██        | 6/30 [11:39<46:40, 116.68s/it]

Epoch 6, Train Loss: 1.2089, Test Loss: 1.1737, Train Acc: 0.8771, Test Acc: 0.8958


 23%|██▎       | 7/30 [13:37<44:57, 117.27s/it]

Epoch 7, Train Loss: 1.1970, Test Loss: 1.1661, Train Acc: 0.8855, Test Acc: 0.9002


 27%|██▋       | 8/30 [15:34<42:59, 117.26s/it]

Epoch 8, Train Loss: 1.1902, Test Loss: 1.1608, Train Acc: 0.8890, Test Acc: 0.9031


 30%|███       | 9/30 [17:33<41:13, 117.81s/it]

Epoch 9, Train Loss: 1.1851, Test Loss: 1.1588, Train Acc: 0.8867, Test Acc: 0.9008


 33%|███▎      | 10/30 [19:30<39:12, 117.60s/it]

Epoch 10, Train Loss: 1.1792, Test Loss: 1.1579, Train Acc: 0.8920, Test Acc: 0.8988


 37%|███▋      | 11/30 [23:13<47:26, 149.81s/it]

Epoch 11, Train Loss: 1.1369, Test Loss: 1.1150, Train Acc: 0.9156, Test Acc: 0.9304


 40%|████      | 12/30 [26:56<51:33, 171.88s/it]

Epoch 12, Train Loss: 1.1116, Test Loss: 1.1095, Train Acc: 0.9366, Test Acc: 0.9351


 43%|████▎     | 13/30 [30:39<53:06, 187.44s/it]

Epoch 13, Train Loss: 1.1011, Test Loss: 1.1069, Train Acc: 0.9455, Test Acc: 0.9387


 47%|████▋     | 14/30 [34:21<52:47, 197.96s/it]

Epoch 14, Train Loss: 1.0919, Test Loss: 1.1058, Train Acc: 0.9550, Test Acc: 0.9384


 50%|█████     | 15/30 [38:04<51:20, 205.35s/it]

Epoch 15, Train Loss: 1.0863, Test Loss: 1.1157, Train Acc: 0.9593, Test Acc: 0.9293


 53%|█████▎    | 16/30 [41:46<49:06, 210.47s/it]

Epoch 16, Train Loss: 1.0839, Test Loss: 1.1045, Train Acc: 0.9621, Test Acc: 0.9384


 57%|█████▋    | 17/30 [45:28<46:20, 213.91s/it]

Epoch 17, Train Loss: 1.0787, Test Loss: 1.1091, Train Acc: 0.9671, Test Acc: 0.9325


 60%|██████    | 18/30 [49:10<43:16, 216.37s/it]

Epoch 18, Train Loss: 1.0743, Test Loss: 1.1090, Train Acc: 0.9712, Test Acc: 0.9341


 63%|██████▎   | 19/30 [52:52<39:59, 218.10s/it]

Epoch 19, Train Loss: 1.0728, Test Loss: 1.1066, Train Acc: 0.9726, Test Acc: 0.9366


 67%|██████▋   | 20/30 [56:34<36:33, 219.38s/it]

Epoch 20, Train Loss: 1.0697, Test Loss: 1.1072, Train Acc: 0.9756, Test Acc: 0.9377


 70%|███████   | 21/30 [1:00:16<33:01, 220.14s/it]

Epoch 21, Train Loss: 1.0699, Test Loss: 1.1052, Train Acc: 0.9757, Test Acc: 0.9387


 73%|███████▎  | 22/30 [1:03:58<29:24, 220.61s/it]

Epoch 22, Train Loss: 1.0665, Test Loss: 1.1035, Train Acc: 0.9792, Test Acc: 0.9399


 77%|███████▋  | 23/30 [1:07:40<25:46, 220.92s/it]

Epoch 23, Train Loss: 1.0661, Test Loss: 1.1063, Train Acc: 0.9788, Test Acc: 0.9393


 80%|████████  | 24/30 [1:11:21<22:07, 221.17s/it]

Epoch 24, Train Loss: 1.0634, Test Loss: 1.1044, Train Acc: 0.9819, Test Acc: 0.9379


 83%|████████▎ | 25/30 [1:15:04<18:27, 221.44s/it]

Epoch 25, Train Loss: 1.0620, Test Loss: 1.1042, Train Acc: 0.9829, Test Acc: 0.9399


 87%|████████▋ | 26/30 [1:18:45<14:46, 221.59s/it]

Epoch 26, Train Loss: 1.0606, Test Loss: 1.1035, Train Acc: 0.9841, Test Acc: 0.9399


 90%|█████████ | 27/30 [1:22:27<11:04, 221.60s/it]

Epoch 27, Train Loss: 1.0609, Test Loss: 1.1032, Train Acc: 0.9838, Test Acc: 0.9394


 93%|█████████▎| 28/30 [1:26:09<07:23, 221.69s/it]

Epoch 28, Train Loss: 1.0594, Test Loss: 1.1064, Train Acc: 0.9855, Test Acc: 0.9373


 97%|█████████▋| 29/30 [1:29:51<03:41, 221.69s/it]

Epoch 29, Train Loss: 1.0590, Test Loss: 1.1005, Train Acc: 0.9855, Test Acc: 0.9439


100%|██████████| 30/30 [1:33:32<00:00, 187.09s/it]

Epoch 30, Train Loss: 1.0593, Test Loss: 1.1022, Train Acc: 0.9857, Test Acc: 0.9416


(array([1.61717532, 1.35768946, 1.27359237, 1.2385327 , 1.21877538,
        1.20889992, 1.19702936, 1.19015058, 1.18506252, 1.17918133,
        1.13691294, 1.11158177, 1.10106334, 1.09189397, 1.086268  ,
        1.08385523, 1.07872464, 1.07425769, 1.07282956, 1.06966574,
        1.06991312, 1.066483  , 1.06606211, 1.06335202, 1.06202542,
        1.06063521, 1.06091288, 1.05944314, 1.05898595, 1.05925425]),
 array([1.38019052, 1.2465365 , 1.20815468, 1.19006454, 1.17972906,
        1.17374684, 1.16606487, 1.16080782, 1.15881382, 1.15790578,
        1.11502724, 1.10950824, 1.10686472, 1.10578779, 1.11566602,
        1.1045071 , 1.10909968, 1.10904689, 1.10660654, 1.10721463,
        1.10522882, 1.1035242 , 1.10633563, 1.10443056, 1.10415704,
        1.10346321, 1.10322707, 1.10644639, 1.10048554, 1.10222687]),
 array([0.61769962, 0.85457796, 0.86714602, 0.87506324, 0.87985641,
        0.87705642, 0.88552737, 0.88903922, 0.88666636, 0.89198941,
        0.91555148, 0.93660623, 0.94554383, 

In [87]:
train_losses=[]
test_losses=[]
def accuracy_final(loader, model):
    num_corrects = 0
    num_samples = 0
    model.eval()
    loop = tqdm(loader)
    with torch.no_grad():
        for x, y in loop:
            x = x.to(device)
            y = y.to(device)
            scores = model(x)
            test_losses.append(scores.data)
            _, prediction = scores.max(1)
            num_corrects += (prediction == y).sum()
            num_samples += prediction.size(0)
            acc = (num_corrects/num_samples) * 100
            loop.set_postfix(acc=acc.item())
        print(f'Got {num_corrects}/{num_samples} with accuracy {acc:.4f}')

accuracy_mehrdad(test_loader, model)

100%|██████████| 94/94 [00:18<00:00,  5.18it/s, acc=94.2]

Got 2825/3000 with accuracy 94.1667


lets try another aproach

In [13]:
model = models.resnet152(pretrained=True)
print(model)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [14]:
model = models.resnet152(pretrained=True)
print(model)
freeze_or_un_freeze(model)
n = model.fc.in_features
print(n)
model.fc = nn.Sequential(
    nn.Dropout(0.2),
    nn.Linear(n, 512), 
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(512, 6),
    nn.Softmax(),
)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.00001, betas=(0, 0.999))

2048


In [15]:
model.to(device)
train(model, criterion, optimizer, train_loader, test_loader, 30, 10)

  3%|▎         | 1/30 [03:27<1:40:03, 207.02s/it]

Epoch 1, Train Loss: 1.6215, Test Loss: 1.3869, Train Acc: 0.6249, Test Acc: 0.8756


  7%|▋         | 2/30 [05:49<1:18:53, 169.04s/it]

Epoch 2, Train Loss: 1.3674, Test Loss: 1.2564, Train Acc: 0.8492, Test Acc: 0.8789


 10%|█         | 3/30 [08:11<1:10:28, 156.60s/it]

Epoch 3, Train Loss: 1.2830, Test Loss: 1.2129, Train Acc: 0.8640, Test Acc: 0.8875


 13%|█▎        | 4/30 [10:33<1:05:26, 151.01s/it]

Epoch 4, Train Loss: 1.2443, Test Loss: 1.1946, Train Acc: 0.8749, Test Acc: 0.8882


 17%|█▋        | 5/30 [12:55<1:01:30, 147.64s/it]

Epoch 5, Train Loss: 1.2247, Test Loss: 1.1828, Train Acc: 0.8752, Test Acc: 0.8932


 20%|██        | 6/30 [15:17<58:19, 145.82s/it]  

Epoch 6, Train Loss: 1.2090, Test Loss: 1.1755, Train Acc: 0.8836, Test Acc: 0.8925


 23%|██▎       | 7/30 [17:39<55:23, 144.50s/it]

Epoch 7, Train Loss: 1.1989, Test Loss: 1.1716, Train Acc: 0.8867, Test Acc: 0.8915


 27%|██▋       | 8/30 [20:01<52:45, 143.87s/it]

Epoch 8, Train Loss: 1.1926, Test Loss: 1.1660, Train Acc: 0.8892, Test Acc: 0.8952


 30%|███       | 9/30 [22:23<50:07, 143.21s/it]

Epoch 9, Train Loss: 1.1865, Test Loss: 1.1620, Train Acc: 0.8891, Test Acc: 0.8948


 33%|███▎      | 10/30 [24:45<47:32, 142.62s/it]

Epoch 10, Train Loss: 1.1825, Test Loss: 1.1583, Train Acc: 0.8887, Test Acc: 0.8998


 37%|███▋      | 11/30 [29:44<1:00:23, 190.71s/it]

Epoch 11, Train Loss: 1.1404, Test Loss: 1.1120, Train Acc: 0.9122, Test Acc: 0.9341


 40%|████      | 12/30 [34:43<1:07:06, 223.69s/it]

Epoch 12, Train Loss: 1.1097, Test Loss: 1.1063, Train Acc: 0.9376, Test Acc: 0.9382


 43%|████▎     | 13/30 [39:43<1:09:55, 246.77s/it]

Epoch 13, Train Loss: 1.0982, Test Loss: 1.1016, Train Acc: 0.9495, Test Acc: 0.9437


 47%|████▋     | 14/30 [44:43<1:10:05, 262.87s/it]

Epoch 14, Train Loss: 1.0912, Test Loss: 1.1064, Train Acc: 0.9553, Test Acc: 0.9356


 50%|█████     | 15/30 [49:43<1:08:31, 274.07s/it]

Epoch 15, Train Loss: 1.0869, Test Loss: 1.1057, Train Acc: 0.9599, Test Acc: 0.9385


 53%|█████▎    | 16/30 [54:43<1:05:43, 281.66s/it]

Epoch 16, Train Loss: 1.0813, Test Loss: 1.1049, Train Acc: 0.9645, Test Acc: 0.9384


 57%|█████▋    | 17/30 [59:42<1:02:11, 287.07s/it]

Epoch 17, Train Loss: 1.0745, Test Loss: 1.1063, Train Acc: 0.9714, Test Acc: 0.9382


 60%|██████    | 18/30 [1:04:42<58:09, 290.80s/it]

Epoch 18, Train Loss: 1.0726, Test Loss: 1.1042, Train Acc: 0.9725, Test Acc: 0.9402


 63%|██████▎   | 19/30 [1:09:42<53:49, 293.55s/it]

Epoch 19, Train Loss: 1.0714, Test Loss: 1.1025, Train Acc: 0.9737, Test Acc: 0.9432


 67%|██████▋   | 20/30 [1:14:42<49:14, 295.43s/it]

Epoch 20, Train Loss: 1.0679, Test Loss: 1.1033, Train Acc: 0.9774, Test Acc: 0.9415


 70%|███████   | 21/30 [1:19:41<44:30, 296.78s/it]

Epoch 21, Train Loss: 1.0664, Test Loss: 1.1053, Train Acc: 0.9785, Test Acc: 0.9394


 73%|███████▎  | 22/30 [1:24:41<39:41, 297.70s/it]

Epoch 22, Train Loss: 1.0647, Test Loss: 1.1041, Train Acc: 0.9801, Test Acc: 0.9384


 77%|███████▋  | 23/30 [1:29:41<34:48, 298.30s/it]

Epoch 23, Train Loss: 1.0640, Test Loss: 1.1065, Train Acc: 0.9809, Test Acc: 0.9354


 80%|████████  | 24/30 [1:34:42<29:54, 299.11s/it]

Epoch 24, Train Loss: 1.0624, Test Loss: 1.1017, Train Acc: 0.9826, Test Acc: 0.9410


 83%|████████▎ | 25/30 [1:39:43<24:57, 299.53s/it]

Epoch 25, Train Loss: 1.0604, Test Loss: 1.1006, Train Acc: 0.9844, Test Acc: 0.9433


 87%|████████▋ | 26/30 [1:44:43<19:58, 299.69s/it]

Epoch 26, Train Loss: 1.0603, Test Loss: 1.1012, Train Acc: 0.9842, Test Acc: 0.9432


 90%|█████████ | 27/30 [1:49:42<14:58, 299.48s/it]

Epoch 27, Train Loss: 1.0608, Test Loss: 1.1100, Train Acc: 0.9836, Test Acc: 0.9357


 93%|█████████▎| 28/30 [1:54:41<09:59, 299.50s/it]

Epoch 28, Train Loss: 1.0594, Test Loss: 1.1033, Train Acc: 0.9846, Test Acc: 0.9429


 97%|█████████▋| 29/30 [1:59:41<04:59, 299.50s/it]

Epoch 29, Train Loss: 1.0589, Test Loss: 1.1058, Train Acc: 0.9858, Test Acc: 0.9366


100%|██████████| 30/30 [2:04:41<00:00, 249.37s/it]

Epoch 30, Train Loss: 1.0587, Test Loss: 1.1071, Train Acc: 0.9855, Test Acc: 0.9381


(array([1.62154042, 1.36742133, 1.28303813, 1.24429846, 1.22469136,
        1.20899252, 1.19890135, 1.19259588, 1.18652643, 1.18252647,
        1.14035904, 1.10974678, 1.09822216, 1.09121622, 1.08685227,
        1.08126099, 1.07449165, 1.07263337, 1.07144574, 1.06793341,
        1.06637014, 1.06471122, 1.06400162, 1.06236949, 1.06044867,
        1.06034315, 1.06081196, 1.05937214, 1.05887232, 1.05869326]),
 array([1.38694091, 1.25638575, 1.21290524, 1.1946052 , 1.18283801,
        1.17552867, 1.17157473, 1.16601787, 1.16201164, 1.15831631,
        1.11196652, 1.10633051, 1.10159806, 1.10636146, 1.10570289,
        1.10486785, 1.1062826 , 1.10418904, 1.10251463, 1.1032901 ,
        1.10529004, 1.10408998, 1.10651004, 1.10174267, 1.10064325,
        1.101247  , 1.11004928, 1.10328191, 1.10581246, 1.10712837]),
 array([0.62493676, 0.84924704, 0.86397433, 0.87490511, 0.87517399,
        0.8836292 , 0.88673753, 0.8891657 , 0.88907081, 0.88873863,
        0.91224533, 0.93758702, 0.94945902, 

okay this got worse so lets not use this aproach and lets stick to our first model

by the way sorry for not plotting the loss and accuracy on epoch i forgot to take the return and well now its too latr

In [ ]:
train(model, criterion, optimizer, train_loader, test_loader, 15, 5)

  7%|▋         | 1/15 [04:59<1:09:48, 299.18s/it]

Epoch 1, Train Loss: 1.0578, Test Loss: 1.1083, Train Acc: 0.9866, Test Acc: 0.9342


 13%|█▎        | 2/15 [09:58<1:04:54, 299.54s/it]

Epoch 2, Train Loss: 1.0571, Test Loss: 1.1038, Train Acc: 0.9873, Test Acc: 0.9387


 20%|██        | 3/15 [14:58<59:55, 299.65s/it]  

Epoch 3, Train Loss: 1.0561, Test Loss: 1.1032, Train Acc: 0.9881, Test Acc: 0.9419


 27%|██▋       | 4/15 [19:58<54:54, 299.51s/it]

Epoch 4, Train Loss: 1.0571, Test Loss: 1.1064, Train Acc: 0.9870, Test Acc: 0.9369


 33%|███▎      | 5/15 [24:57<49:55, 299.51s/it]

Epoch 5, Train Loss: 1.0573, Test Loss: 1.1106, Train Acc: 0.9867, Test Acc: 0.9328


In [ ]:
model2 = models.resnet34(pretrained=True)
print(model2)
freeze_or_un_freeze(model2)
n = model2.fc.in_features
print(n)
model2.fc = nn.Sequential(
    nn.Dropout(0.2),
    nn.Linear(n, 512), 
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(512, 6),
    nn.Softmax(),
)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model2.parameters(), lr=0.00001, betas=(0, 0.999))
train(model, criterion, optimizer, train_loader, test_loader, 30, 10)